### ISSUE TITLE
Create a Production Server

### ISSUE THREAD

**Issue by soupglasses** [cs-24-sw-3-15/contract-service#39]
Create a server running in production using `postgresql`, `letsencrypt`, `nginx`, and other goodies. Ensure its running in production mode and through systemd.

We can get a server from ITS using [Strato New](https://strato-new.claaudia.aau.dk/auth/login/?next=/project/).

**Comment by soupglasses** [comment]
This has now been created. Missing features from a quick lookover.
- Email?
- ActiveJob?
- File preview

**Comment by krestenlaust** [comment]
> This has now been created. Missing features from a quick lookover.
> 
>     * Email?
> 
>     * ActiveJob?
> 
>     * File preview

New issue?
